# Generated by Django 5.1.2 on 2024-11-16 20:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0003_category_contact_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
    ]
